export const db= "software-circuit"
export const questionCollection= "questions"
export const answerCollection= "answer"
export const voteCollection= "votes"
export const questionAttachementBucket= "question-attachement"
export const commentCollection= "comments"
